### ISSUE TITLE
error al registrar pedido

### ISSUE THREAD

**Issue by baltazarAvave** [evervf/TP_Android#1]
@evervf : Cuando pruebo desde el emulador, la aplicación explota al presionar el boton Registrar Pedido, parece ser un herror de conversión de tipo al guardar en la tabla:
`
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.NoClassDefFoundError: android.icu.text.SimpleDateFormat
                      at com.example.ever.myapplication.sqlite.OperacionesBaseDatos.insetarVenta(OperacionesBaseDatos.java:100)
                      at com.example.ever.myapplication.LevantamientoPedido.onClick(LevantamientoPedido.java:166)
                      at android.view.View.performClick(View.java:4084)
                      at android.view.View$PerformClick.run(View.java:16966)
                      at android.os.Handler.handleCallback(Handler.java:615)
                      at android.os.Handler.dispatchMessage(Handler.java:92)
                      at android.os.Looper.loop(Looper.java:137)
                      at android.app.ActivityThread.main(ActivityThread.java:4745)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:511)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                      at dalvik.system.NativeStart.main(Native Method)
Application terminated.´
`

**Comment by evervf** [comment]
@baltazarAvave : Que tal profe. Ahora acabo de desinstalar la aplicación de mi teléfono borrando la base de datos ya creada y a mi no me genera ningún error.

**Comment by baltazarAvave** [comment]
hola @evervf capaz la versión que esta en el github no es la ultima, yo descargué de ahí y generé la apk,
en mi telefono tampoco funciona, podrías adjuntar la apk que estas usando para probar?

**Comment by evervf** [comment]
@baltazarAvave  profe, te envié a tu correo porque acá no me deja alzar ni en .zip
